defaults: &defaults
  docker:
    - image: taijuten/circle-node-awscli:latest
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: s3 deploy
          command: aws s3 sync "./templates" "s3://$AWS_CLOUDFORMATION_TEMPLATES_S3_BUCKET/master" --exclude "*" --include "*.yml"
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
                only: master
          context: aws
