defaults: &defaults
  docker:
    - image: circleci/node:8.10.0
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: s3 deploy
          command: aws s3 sync "./templates" "s3://$AWS_CLOUDFORMATION_TEMPLATES_S3_BUCKET/master" --exclude "*" --include "*.yml"
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
                only: master
