AWSTemplateFormatVersion: 2010-09-09
Description: api-gateway-alerting

Parameters:

  NestedStackTemplateLocation:
    Description: The HTTPS URL for the S3 bucket containing the Cloudformation for nested stacks
    Type: String
    AllowedPattern: .+

  ApiGateway:
    Description: The name of the Api Gateway resource defined in the calling template. This is required.
    Type: String
    AllowedPattern: .+

  ApiGateway5XXErrorsAlarmName:
    Description: The name of the Api Gateway 5XXErrors alarm
    Type: String
    Default: ""
  ApiGateway5XXErrorsAlarmPeriod:
    Description: The period over which the Api Gateway 5XXErrors alarm applies
    Type: String
    Default: ""
  ApiGateway5XXErrorsAlarmThreshold:
    Description: The threshold for the Api Gateway 5XXErrors alarm
    Type: String
    Default: ""

  AlarmEmailAddress:
    Description: The email address intended to receive alerts raised by the defined Cloudwatch alarms. It is not intended for this parameter to be changed.
    Type: String
    Default: development@zerojargon.com
    AllowedPattern: .+

Conditions:

  ShouldCreate5XXErrorsAlarm: !And
    - !Not [ !Equals [ !Ref ApiGateway5XXErrorsAlarmName, "" ] ]
    - !Not [ !Equals [ !Ref ApiGateway5XXErrorsAlarmPeriod, "" ] ]
    - !Not [ !Equals [ !Ref ApiGateway5XXErrorsAlarmThreshold, "" ] ]

Resources:

  CloudwatchApiGatewayAlarmSnsEmailTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref AlarmEmailAddress
          Protocol: email

  CloudwatchAlarmApiGateway5XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: ShouldCreate5XXErrorsAlarm
    Properties:
      AlarmActions:
        - !Ref CloudwatchApiGatewayAlarmSnsEmailTopic
      AlarmDescription: !Join [ " ", [ "Api Gateway 5XX errors alarm for ", !Ref "ApiGateway" ] ]
      AlarmName: !Ref ApiGateway5XXErrorsAlarmName
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref ApiGateway
      EvaluationPeriods: 1
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Period: !Ref ApiGateway5XXErrorsAlarmPeriod
      Statistic: Average
      Threshold: !Ref ApiGateway5XXErrorsAlarmThreshold
      TreatMissingData: notBreaching

  CloudwatchApiGatewayAlarmSnsFailureAlertingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ "", [ !Ref "NestedStackTemplateLocation", "/alerting/sns-alerting.yml" ] ]
      Parameters:
        SnsTopic: !Ref CloudwatchApiGatewayAlarmSnsEmailTopic
        SnsFailuresAlarmName: !Join [ "-", [ !Ref "AWS::StackName", !Ref "ApiGateway", sns ] ]
        SnsFailuresAlarmPeriod: 86400
        SnsFailuresAlarmThreshold: 1
