AWSTemplateFormatVersion: 2010-09-09
Description: lambda-alerting

Parameters:

  NestedStackTemplateLocation:
    Description: The HTTPS URL for the S3 bucket containing the Cloudformation for nested stacks
    Type: String
    AllowedPattern: .+

  LambdaFunction:
    Description: The name of the Lambda Function resource defined in the calling template. This is required.
    Type: String
    AllowedPattern: .+

  LambdaInvocationsAlarmName:
    Description: The name of the Lambda invocations alarm
    Type: String
    Default: ""
  LambdaInvocationsAlarmPeriod:
    Description: The period over which the Lambda invocations alarm applies
    Type: String
    Default: ""
  LambdaInvocationsAlarmThreshold:
    Description: The threshold for the Lambda invocations alarm
    Type: String
    Default: ""

  LambdaErrorsAlarmName:
    Description: The name of the Lambda errors alarm
    Type: String
    Default: ""
  LambdaErrorsAlarmPeriod:
    Description: The period over which the Lambda errors alarm applies
    Type: String
    Default: ""
  LambdaErrorsAlarmThreshold:
    Description: The threshold for the Lambda errors alarm
    Type: String
    Default: ""

  AlarmEmailAddress:
    Description: The email address intended to receive alerts raised by the defined Cloudwatch alarms. It is not intended for this parameter to be changed.
    Type: String
    Default: development@zerojargon.com
    AllowedPattern: .+

Conditions:

  ShouldCreateInvocationsAlarm: !And
    - !Not [ !Equals [ !Ref LambdaInvocationsAlarmName, "" ] ]
    - !Not [ !Equals [ !Ref LambdaInvocationsAlarmPeriod, "" ] ]
    - !Not [ !Equals [ !Ref LambdaInvocationsAlarmThreshold, "" ] ]

  ShouldCreateErrorsAlarm: !And
    - !Not [ !Equals [ !Ref LambdaErrorsAlarmName, "" ] ]
    - !Not [ !Equals [ !Ref LambdaErrorsAlarmPeriod, "" ] ]
    - !Not [ !Equals [ !Ref LambdaErrorsAlarmThreshold, "" ] ]

Resources:

  CloudwatchLambdaAlarmSnsEmailTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref AlarmEmailAddress
          Protocol: email

  CloudwatchAlarmLambdaFunctionInvocationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: ShouldCreateInvocationsAlarm
    Properties:
      AlarmActions:
        - !Ref CloudwatchLambdaAlarmSnsEmailTopic
      AlarmDescription: !Join [ " ", [ "Lambda invocation alarm for ", !Ref "LambdaFunction" ] ]
      AlarmName: !Ref LambdaInvocationsAlarmName
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunction
      EvaluationPeriods: 1
      MetricName: Invocations
      Namespace: AWS/Lambda
      Period: !Ref LambdaInvocationsAlarmPeriod
      Statistic: Sum
      Threshold: !Ref LambdaInvocationsAlarmThreshold
      TreatMissingData: breaching

  CloudwatchAlarmLambdaFunctionErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: ShouldCreateErrorsAlarm
    Properties:
      AlarmActions:
        - !Ref CloudwatchLambdaAlarmSnsEmailTopic
      AlarmDescription: !Join [ " ", [ "Lambda error alarm for ", !Ref "LambdaFunction" ] ]
      AlarmName: !Ref LambdaErrorsAlarmName
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
          - Name: FunctionName
            Value: !Ref LambdaFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: !Ref LambdaErrorsAlarmPeriod
      Statistic: Sum
      Threshold: !Ref LambdaErrorsAlarmThreshold
      TreatMissingData: notBreaching

  CloudwatchLambdaAlarmSnsFailureAlertingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ "", [ !Ref "NestedStackTemplateLocation", "/alerting/sns-alerting.yml" ] ]
      Parameters:
        SnsTopic: !Ref CloudwatchLambdaAlarmSnsEmailTopic
        SnsFailuresAlarmName: !Join [ "-", [ !Ref "AWS::StackName", !Ref "LambdaFunction", sns ] ]
        SnsFailuresAlarmPeriod: 86400
        SnsFailuresAlarmThreshold: 1
